export const FETCH_PLAYERS_SUCCESS = 'FETCH_PLAYERS_SUCCESS'
export const FETCH_PLAYERS_REQUEST = 'FETCH_PLAYERS_REQUEST'
export const FETCH_PLAYERS_ERROR = 'FETCH_PLAYERS_ERROR'
export const SELECTED_PLAYER = 'SELECTED_PLAYER'
export const DELETE_PLAYER = 'DELETE_PLAYER'

export const CREATE_CAPTAIN = 'CREATE_CAPTAIN'
export const CREATE_VICE_CAPTAIN = 'CREATE_VICE_CAPTAIN'

export const POST_PLAYERS_SUCCESS = 'POST_PLAYERS_SUCCESS'
